Traceback (most recent call last):
  File "/home/janulm/janulm_agent_nodes/traditional_gcn/gcn_ogb_arxiv.py", line 177, in <module>
    print("max result test acc: ",results[np.argmax(results)],np.argmax(results))
IndexError: index 5 is out of bounds for axis 0 with size 4
